---
language: ruby

bundler_args: --without system_tests

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.6.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.7.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.8.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.9.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.10.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4"

notifications:
  email: false
