---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  exclude:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"